(function () {
  const byId = id => document.getElementById(id);
  const token = () => window.ScannerBackend?.state?.session?.access_token || "";
  const esc = value => String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
  async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json", ...options.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Erro ${response.status}`); return data; }
  function performance(rows) {
    const settled = rows.filter(row => row.bet_status && row.bet_status !== "Open"), stake = settled.reduce((sum, row) => sum + Number(row.stake || 0), 0), profit = settled.reduce((sum, row) => sum + Number(row.profit || 0), 0);
    const greens = settled.filter(row => ["Won", "Half Won"].includes(row.bet_status)).length, reds = settled.filter(row => ["Lost", "Half Lost"].includes(row.bet_status)).length;
    let current = 0, best = 0, drawdown = 0, peak = 0, equity = 0;
    settled.slice().reverse().forEach(row => { equity += Number(row.profit || 0); peak = Math.max(peak, equity); drawdown = Math.min(drawdown, equity - peak); if (["Won", "Half Won"].includes(row.bet_status)) { current++; best = Math.max(best, current); } else current = 0; });
    return { settled, stake, profit, greens, reds, voids: settled.filter(row => row.bet_status === "Void").length, winRate: settled.length ? greens / settled.length * 100 : 0, roi: stake ? profit / stake * 100 : 0, drawdown, best, current, averageOdd: rows.length ? rows.reduce((sum, row) => sum + Number(row.entry_odd || 0), 0) / rows.length : 0 };
  }
  async function renderHome() {
    const root = byId("dashboard-page");
    if (!token()) { root.innerHTML = '<section class="panel premium-empty"><h2>Carregando seu painel…</h2></section>'; return; }
    try {
      const [analyses, bets] = await Promise.all([api("/api/analyses?limit=200"), api("/api/suggested-bets")]), p = performance(bets), today = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo" }).format(new Date()), daily = analyses.filter(row => row.match_date === today), approved = daily.filter(row => row.official_entry), monitor = daily.filter(row => !row.official_entry && !["Rejected", "Reprovado"].includes(row.classification)), best = daily.slice().sort((a,b) => Number(b.scanner_score)-Number(a.scanner_score))[0];
      root.innerHTML = `<div class="page-heading"><div><p class="eyebrow">SCANNERDAY</p><h1>Visão geral</h1><p>Análises da metodologia de favoritos visitantes e desempenho das apostas oficiais.</p></div></div><div class="kpis"><article class="simple-kpi"><span>ANÁLISES HOJE</span><strong>${daily.length}</strong></article><article class="simple-kpi"><span>APROVADAS / MONITOR</span><strong>${approved.length} / ${monitor.length}</strong></article><article class="simple-kpi"><span>APOSTAS ABERTAS</span><strong>${bets.filter(row => (row.bet_status||"Open") === "Open").length}</strong></article><article class="simple-kpi"><span>MELHOR SCORE</span><strong>${best ? best.scanner_score : "—"}</strong></article></div><div class="grid-main"><section class="panel"><div class="panel-head"><div><h2>Melhores análises de hoje</h2><p>Entradas aprovadas ordenadas pelo ScannerScore.</p></div></div>${approved.length ? approved.slice(0,5).map(row => `<div class="mvp-result-row"><div><strong>${esc(row.home_team)} × ${esc(row.away_team)}</strong><small>${esc(row.competition)}</small></div><span>${esc(row.selection)}</span><span>Odd ${Number(row.market_odd).toFixed(2)}</span><strong>Score ${row.scanner_score}</strong></div>`).join("") : '<div class="admin-empty">Nenhuma entrada aprovada hoje.</div>'}</section><section class="panel"><div class="panel-head"><div><h2>Performance das apostas sugeridas</h2><p>Não inclui resultados do Scanner.</p></div></div><div class="mvp-result-kpis"><article class="simple-kpi"><span>WIN RATE</span><strong>${p.settled.length?p.winRate.toFixed(1)+"%":"—"}</strong></article><article class="simple-kpi"><span>ROI / YIELD</span><strong>${p.settled.length?p.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>LUCRO</span><strong>${p.profit.toFixed(2)}u</strong></article></div></section></div>`;
      root.querySelector(".page-heading")?.insertAdjacentHTML("afterend", `<section class="panel mvp-hero strategy-card"><span>NOSSA ESTRATÉGIA</span><h2>Favoritos visitantes, analisados com método.</h2><p>O ScannerDay avalia exclusivamente equipes <strong>visitantes favoritas</strong>, normalmente dentro da faixa de odds entre <strong>1.20 e 1.65</strong>. Cada partida passa por critérios de força do elenco, forma recente, desempenho fora de casa, valor da odd, xG, desfalques, motivação e confronto direto.</p><p>O <strong>ScannerScore</strong> resume a qualidade da oportunidade de 0 a 100. Análises aprovadas atendem aos critérios da metodologia; jogos em monitoramento ainda exigem confirmação. Probabilidade, odd justa, EV, confiança e risco devem ser interpretados em conjunto — nenhuma análise representa garantia de resultado.</p></section>`);
    } catch (error) { root.innerHTML = `<section class="panel admin-empty">${esc(error.message)}</section>`; }
  }
  async function renderResults() { const root = byId("mvpResults"); try { const rows = await api("/api/suggested-bets"), p = performance(rows); root.innerHTML = `<div class="mvp-result-kpis"><article class="simple-kpi"><span>TOTAL</span><strong>${rows.length}</strong></article><article class="simple-kpi"><span>GREENS / REDS / VOIDS</span><strong>${p.greens} / ${p.reds} / ${p.voids}</strong></article><article class="simple-kpi"><span>WIN RATE</span><strong>${p.settled.length?p.winRate.toFixed(1)+"%":"—"}</strong></article><article class="simple-kpi"><span>ROI / YIELD</span><strong>${p.settled.length?p.roi.toFixed(2)+"%":"—"}</strong></article></div><section class="panel"><div class="panel-head"><div><h2>Indicadores financeiros</h2><p>Stake ${p.stake.toFixed(2)}u · odd média ${p.averageOdd.toFixed(2)} · drawdown ${p.drawdown.toFixed(2)}u · melhor sequência ${p.best}</p></div></div>${p.settled.length?p.settled.map(row=>`<div class="mvp-result-row"><div><strong>${esc(row.match_name||[row.home_team,row.away_team].filter(Boolean).join(" × "))}</strong><small>${esc(row.tip_id)}</small></div><span>${esc(row.selection)}</span><span>${Number(row.entry_odd).toFixed(2)}</span><span>${esc(row.bet_status)}</span><strong class="${Number(row.profit)>=0?"green-text":"red-text"}">${Number(row.profit||0).toFixed(2)}u</strong></div>`).join(""):'<div class="admin-empty">Nenhuma aposta liquidada.</div>'}</section>`; } catch(error) { root.innerHTML=`<section class="panel admin-empty">${esc(error.message)}</section>`; } }
  async function renderUsers() { const root=byId("adminUsersTable"); try { const rows=await api("/api/admin-users"); root.innerHTML=`<div class="mvp-user-row mvp-user-head"><span>USUÁRIO</span><span>PERFIL</span><span>CADASTRO</span><span>STATUS</span><span>ÚLTIMO ACESSO</span><span>AÇÕES</span></div>${rows.map(row=>`<div class="mvp-user-row"><div><strong>${esc(row.name||row.email)}</strong><small>${esc(row.email)}</small></div><span>${row.role==="admin"?"Administrador":"Usuário"}</span><span>${new Date(row.created_at).toLocaleDateString("pt-BR")}</span><span>${row.confirmed_at?"Ativo":"Pendente"}</span><span>${row.last_sign_in_at?new Date(row.last_sign_in_at).toLocaleString("pt-BR"):"—"}</span><div class="user-actions">${row.is_current_user?'<small>Conta protegida</small>':`<button data-user-role="${row.id}" data-next-role="${row.role==="admin"?"user":"admin"}">${row.role==="admin"?"Tornar usuário":"Tornar admin"}</button><button class="danger" data-delete-user="${row.id}">Excluir</button>`}</div></div>`).join("")}`; root.querySelectorAll("[data-user-role]").forEach(button=>button.onclick=async()=>{await api("/api/admin-users",{method:"PATCH",body:JSON.stringify({id:button.dataset.userRole,role:button.dataset.nextRole})});renderUsers();}); root.querySelectorAll("[data-delete-user]").forEach(button=>button.onclick=async()=>{if(confirm("Excluir definitivamente este usuário?")){await api(`/api/admin-users?id=${encodeURIComponent(button.dataset.deleteUser)}`,{method:"DELETE"});renderUsers();}}); } catch(error){root.innerHTML=`<div class="admin-empty">${esc(error.message)}</div>`;} }
  async function renderAdmin() { const root=byId("adminDashboardContent"); try { const [users,analyses,bets,imports]=await Promise.all([api("/api/admin-users"),api("/api/analyses?limit=200"),api("/api/suggested-bets"),api("/api/imports")]), last=imports[0], settled=bets.filter(row=>(row.bet_status||"Open")!=="Open"); root.innerHTML=`<div class="admin-mvp-kpis"><article class="simple-kpi"><span>USUÁRIOS / ATIVOS</span><strong>${users.length} / ${users.filter(u=>u.confirmed_at).length}</strong></article><article class="simple-kpi"><span>ANÁLISES</span><strong>${analyses.length}</strong></article><article class="simple-kpi"><span>APOSTAS / RESULTADOS</span><strong>${bets.length} / ${settled.length}</strong></article><article class="simple-kpi"><span>BANCO E APIs</span><strong class="green-text">ONLINE</strong></article></div><section class="panel admin-mvp-summary"><h2>Última importação</h2><p>${last?`${esc(last.file_name)} · ${new Date(last.imported_at).toLocaleString("pt-BR")}`:"Nenhuma importação realizada."}</p><p class="green-text">Nenhum erro operacional registrado nesta sessão.</p></section>`; } catch(error){root.innerHTML=`<section class="panel admin-empty">${esc(error.message)}</section>`;} }
  async function renderSuggestedAnalytics(){ try { const rows=await api("/api/suggested-bets"),p=performance(rows),page=byId("scanner-analytics-page"); let root=byId("suggestedAnalytics"); if(!root){root=document.createElement("section");root.id="suggestedAnalytics";root.className="panel suggested-analytics";page.appendChild(root);} root.innerHTML=`<div class="panel-head"><div><h2>Performance das apostas sugeridas</h2><p>Financeiro independente dos resultados do Scanner.</p></div></div><div class="kpis"><article class="simple-kpi"><span>LIQUIDADAS</span><strong>${p.settled.length}</strong></article><article class="simple-kpi"><span>WIN RATE</span><strong>${p.settled.length?p.winRate.toFixed(1)+"%":"—"}</strong></article><article class="simple-kpi"><span>ROI / YIELD</span><strong>${p.settled.length?p.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>LUCRO / DRAWDOWN</span><strong>${p.profit.toFixed(2)}u / ${p.drawdown.toFixed(2)}u</strong></article><article class="simple-kpi"><span>STAKE / ODD MÉDIA</span><strong>${p.stake.toFixed(2)}u / ${p.averageOdd.toFixed(2)}</strong></article><article class="simple-kpi"><span>MELHOR SEQUÊNCIA</span><strong>${p.best}</strong></article></div>`; } catch(error){ console.warn(error.message); } }
  renderHome(); window.addEventListener("scannerday:authenticated",renderHome); document.querySelector('[data-page="dashboard"]')?.addEventListener("click",renderHome); document.querySelector('[data-page="results"]')?.addEventListener("click",renderResults); document.querySelector('[data-page="scanner-analytics"]')?.addEventListener("click",renderSuggestedAnalytics); document.querySelector('[data-page="admin-users"]')?.addEventListener("click",renderUsers); document.querySelector('[data-page="admin-dashboard"]')?.addEventListener("click",renderAdmin);
})();
