(function () {
  const byId=id=>document.getElementById(id), escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const token=()=>window.ScannerBackend?.state?.session?.access_token||"";
  const statusLabel={Open:"ABERTA",Won:"GREEN",Lost:"RED",Void:"PUSH","Half Won":"MEIO GREEN","Half Lost":"MEIO RED"};
  function notify(title,detail){const element=byId("toast");element.querySelector("strong").textContent=title;element.querySelector("small").textContent=detail;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),4000);}
  async function api(url,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...options.headers}}),data=await response.json();if(!response.ok)throw new Error(data.error||`Erro ${response.status}`);return data;}
  function metrics(rows){const settled=rows.filter(row=>row.bet_status!=="Open"),stake=settled.reduce((sum,row)=>sum+Number(row.stake||0),0),profit=settled.reduce((sum,row)=>sum+Number(row.profit||0),0),wins=settled.filter(row=>["Won","Half Won"].includes(row.bet_status)).length;return{total:rows.length,open:rows.length-settled.length,settled:settled.length,stake,profit,roi:stake?profit/stake*100:0,winRate:settled.length?wins/settled.length*100:0,greens:wins,reds:settled.filter(row=>["Lost","Half Lost"].includes(row.bet_status)).length,pushes:settled.filter(row=>row.bet_status==="Void").length};}
  function renderPerformance(rows){const value=metrics(rows),stats=document.querySelector("#stats-page .kpis");if(stats)stats.innerHTML=`<article class="simple-kpi"><span>TAXA DE ACERTO</span><strong>${value.settled?value.winRate.toFixed(1)+"%":"—"}</strong></article><article class="simple-kpi"><span>ROI</span><strong>${value.settled?value.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>YIELD</span><strong>${value.settled?value.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>LUCRO</span><strong class="${value.profit>=0?"green-text":"red-text"}">${value.settled?value.profit.toFixed(2)+"u":"—"}</strong></article>`;const finance=byId("finance-page");if(finance)finance.innerHTML=`<div class="page-heading"><div><p class="eyebrow">GESTÃO DE BANCA</p><h1>Dashboard financeiro</h1><p>Métricas calculadas exclusivamente com apostas liquidadas.</p></div></div><div class="kpis"><article class="simple-kpi"><span>VOLUME LIQUIDADO</span><strong>${value.stake.toFixed(2)}u</strong></article><article class="simple-kpi"><span>LUCRO</span><strong class="${value.profit>=0?"green-text":"red-text"}">${value.profit.toFixed(2)}u</strong></article><article class="simple-kpi"><span>GREENS / REDS</span><strong>${value.greens} / ${value.reds}</strong></article><article class="simple-kpi"><span>PUSHES</span><strong>${value.pushes}</strong></article></div>`;}
  async function loadSuggestedBets(){if(!token())return;const grid=byId("suggestedBetsGrid");try{const rows=await api("/api/suggested-bets");renderPerformance(rows);grid.innerHTML=rows.length?rows.map(row=>{const match=row.match_name||[row.home_team,row.away_team].filter(Boolean).join(" × "),status=row.bet_status||"Open";return `<article class="suggested-bet-card panel"><header><div><span class="suggested-label">${escapeHtml(row.tip_id||"APOSTA SUGERIDA")}</span><h2>${escapeHtml(match)}</h2><p>${escapeHtml(row.competition)}${row.match_date?` · ${escapeHtml(row.match_date)}`:""}</p></div><strong class="tip-status status-${status.replace(/\s/g,"-").toLowerCase()}">${statusLabel[status]||escapeHtml(status)}</strong></header><div class="suggested-pick"><span>SELEÇÃO</span><strong>${escapeHtml(row.selection)}</strong><small>${escapeHtml(row.market)}</small></div><div class="suggested-numbers"><div><span>ODD</span><strong>${Number(row.entry_odd).toFixed(2)}</strong></div><div><span>STAKE</span><strong>${Number(row.stake).toFixed(2)}u</strong></div><div><span>${status==="Open"?"CONFIANÇA":"LUCRO"}</span><strong>${status==="Open"?Number(row.confidence)+"%":Number(row.profit||0).toFixed(2)+"u"}</strong></div></div><section><h3>Análise</h3><p>${escapeHtml(row.analysis)}</p>${row.final_score?`<p><strong>Placar final:</strong> ${escapeHtml(row.final_score)}</p>`:""}</section><footer>${row.minimum_entry_odd?`Odd mínima ${Number(row.minimum_entry_odd).toFixed(2)} · `:""}Conteúdo informativo. Aposte com responsabilidade.</footer></article>`;}).join(""):'<section class="panel premium-empty"><h2>Nenhuma aposta publicada</h2><p>As recomendações da equipe aparecerão aqui.</p></section>';}catch(error){grid.innerHTML=`<section class="panel premium-empty"><h2>Não foi possível carregar</h2><p>${escapeHtml(error.message)}</p></section>`;}}
  function fillForm(data){const tip=Array.isArray(data.tips)?data.tips[0]:data,value=(id,...keys)=>{const key=keys.find(item=>tip[item]!==undefined);if(key)byId(id).value=tip[key]??"";},parts=String(tip.match||"").split(/\s+[x×]\s+/i);value("betTipId","tip_id");value("betCompetition","competition");byId("betHomeTeam").value=tip.home_team||parts[0]||"";byId("betAwayTeam").value=tip.away_team||parts[1]||"";value("betMatchDate","match_date","date");value("betMatchTime","match_time","time");value("betMarket","market");value("betSelection","selection","pick");value("betOdd","entry_odd","odd");value("betMinimumOdd","minimum_entry_odd");value("betStake","stake");value("betConfidence","confidence");value("betScannerScore","scanner_score");value("betExpectedValue","expected_value");value("betAnalysis","analysis","reason");value("betInstruction","instruction");}
  async function importFile(file,url,label){const box=byId("suggestedBetError");box.hidden=true;try{const payload=JSON.parse(await file.text()),result=await api(url,{method:"POST",body:JSON.stringify({payload,file_name:file.name})});notify(label,`${result.tips??result.results} registro(s) processado(s).`);await loadSuggestedBets();}catch(error){box.textContent=error.message;box.hidden=false;}}
  byId("selectSuggestedBetFile").onclick=()=>byId("suggestedBetFile").click();byId("suggestedBetFile").onchange=async event=>{const file=event.target.files[0];if(!file)return;byId("suggestedBetFileName").textContent=file.name;await importFile(file,"/api/admin-import-tips","Apostas publicadas");event.target.value="";};
  byId("selectSuggestedResultFile").onclick=()=>byId("suggestedResultFile").click();byId("suggestedResultFile").onchange=async event=>{const file=event.target.files[0];if(!file)return;byId("suggestedResultFileName").textContent=file.name;await importFile(file,"/api/admin-import-results","Resultados liquidados");event.target.value="";};
  byId("suggestedBetForm").onsubmit=async event=>{event.preventDefault();if(!window.ScannerAuth?.isAdmin)return;const button=event.currentTarget.querySelector('[type="submit"]'),errorBox=byId("suggestedBetError");button.disabled=true;button.textContent="Publicando…";errorBox.hidden=true;const payload={tip_id:byId("betTipId").value.trim(),competition:byId("betCompetition").value.trim(),home_team:byId("betHomeTeam").value.trim(),away_team:byId("betAwayTeam").value.trim(),match_date:byId("betMatchDate").value,match_time:byId("betMatchTime").value||null,market:byId("betMarket").value.trim(),selection:byId("betSelection").value.trim(),entry_odd:Number(byId("betOdd").value),minimum_entry_odd:Number(byId("betMinimumOdd").value)||null,stake:Number(byId("betStake").value),confidence:Number(byId("betConfidence").value),scanner_score:Number(byId("betScannerScore").value)||null,expected_value:Number(byId("betExpectedValue").value)||null,analysis:byId("betAnalysis").value.trim(),instruction:byId("betInstruction").value.trim()};try{const result=await api("/api/admin-suggested-bets",{method:"POST",body:JSON.stringify(payload)});event.currentTarget.reset();notify("Aposta publicada",result.tip_id);await loadSuggestedBets();navigate("suggested-bets");}catch(error){errorBox.textContent=error.message;errorBox.hidden=false;}finally{button.disabled=false;button.textContent="Publicar aposta sugerida";}};
  document.querySelector('[data-page="suggested-bets"]').addEventListener("click",loadSuggestedBets);window.addEventListener("scannerday:authenticated",loadSuggestedBets);
})();
