(function () {
  const byId=id=>document.getElementById(id), escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const token=()=>window.ScannerBackend?.state?.session?.access_token||"";
  const statusLabel={Open:"ABERTA",Won:"GREEN",Lost:"RED",Void:"PUSH","Half Won":"MEIO GREEN","Half Lost":"MEIO RED"};
  function notify(title,detail){const element=byId("toast");element.querySelector("strong").textContent=title;element.querySelector("small").textContent=detail;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),4000);}
  async function api(url,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...options.headers}}),data=await response.json();if(!response.ok)throw new Error(data.error||`Erro ${response.status}`);return data;}
  function metrics(rows){const settled=rows.filter(row=>row.bet_status!=="Open"),stake=settled.reduce((sum,row)=>sum+Number(row.stake||0),0),profit=settled.reduce((sum,row)=>sum+Number(row.profit||0),0),wins=settled.filter(row=>["Won","Half Won"].includes(row.bet_status)).length;return{total:rows.length,open:rows.length-settled.length,settled:settled.length,stake,profit,roi:stake?profit/stake*100:0,winRate:settled.length?wins/settled.length*100:0,greens:wins,reds:settled.filter(row=>["Lost","Half Lost"].includes(row.bet_status)).length,pushes:settled.filter(row=>row.bet_status==="Void").length};}
  function renderPerformance(rows){const value=metrics(rows),stats=document.querySelector("#stats-page .kpis");if(stats)stats.innerHTML=`<article class="simple-kpi"><span>TAXA DE ACERTO</span><strong>${value.settled?value.winRate.toFixed(1)+"%":"—"}</strong></article><article class="simple-kpi"><span>ROI</span><strong>${value.settled?value.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>YIELD</span><strong>${value.settled?value.roi.toFixed(2)+"%":"—"}</strong></article><article class="simple-kpi"><span>LUCRO</span><strong class="${value.profit>=0?"green-text":"red-text"}">${value.settled?value.profit.toFixed(2)+"u":"—"}</strong></article>`;const finance=byId("finance-page");if(finance)finance.innerHTML=`<div class="page-heading"><div><p class="eyebrow">GESTÃO DE BANCA</p><h1>Dashboard financeiro</h1><p>Métricas calculadas exclusivamente com apostas liquidadas.</p></div></div><div class="kpis"><article class="simple-kpi"><span>VOLUME LIQUIDADO</span><strong>${value.stake.toFixed(2)}u</strong></article><article class="simple-kpi"><span>LUCRO</span><strong class="${value.profit>=0?"green-text":"red-text"}">${value.profit.toFixed(2)}u</strong></article><article class="simple-kpi"><span>GREENS / REDS</span><strong>${value.greens} / ${value.reds}</strong></article><article class="simple-kpi"><span>PUSHES</span><strong>${value.pushes}</strong></article></div>`;}
  async function loadSuggestedBets(){if(!token())return;const grid=byId("suggestedBetsGrid");try{const rows=await api("/api/suggested-bets");renderPerformance(rows);grid.innerHTML=rows.length?rows.map(row=>{const match=row.match_name||[row.home_team,row.away_team].filter(Boolean).join(" × "),status=row.bet_status||"Open";return `<article class="suggested-bet-card panel"><header><div><span class="suggested-label">${escapeHtml(row.tip_id||"APOSTA SUGERIDA")}</span><h2>${escapeHtml(match)}</h2><p>${escapeHtml(row.competition)}${row.match_date?` · ${escapeHtml(row.match_date)}`:""}</p></div><strong class="tip-status status-${status.replace(/\s/g,"-").toLowerCase()}">${statusLabel[status]||escapeHtml(status)}</strong></header><div class="suggested-pick"><span>SELEÇÃO</span><strong>${escapeHtml(row.selection)}</strong><small>${escapeHtml(row.market)}</small></div><div class="suggested-numbers"><div><span>ODD</span><strong>${Number(row.entry_odd).toFixed(2)}</strong></div><div><span>STAKE</span><strong>${Number(row.stake).toFixed(2)}u</strong></div><div><span>${status==="Open"?"CONFIANÇA":"LUCRO"}</span><strong>${status==="Open"?Number(row.confidence)+"%":Number(row.profit||0).toFixed(2)+"u"}</strong></div></div><section><h3>Análise</h3><p>${escapeHtml(row.analysis)}</p>${row.final_score?`<p><strong>Placar final:</strong> ${escapeHtml(row.final_score)}</p>`:""}</section><footer>${row.minimum_entry_odd?`Odd mínima ${Number(row.minimum_entry_odd).toFixed(2)} · `:""}Conteúdo informativo. Aposte com responsabilidade.</footer>${window.ScannerAuth?.isAdmin?`<button class="suggested-delete" data-delete-tip="${escapeHtml(row.id)}">Excluir aposta</button>`:""}</article>`;}).join(""):'<section class="panel premium-empty"><h2>Nenhuma aposta publicada</h2><p>As recomendações da equipe aparecerão aqui.</p></section>';grid.querySelectorAll("[data-delete-tip]").forEach(button=>button.onclick=async()=>{if(!confirm("Excluir esta aposta sugerida?"))return;try{await api(`/api/admin-suggested-bets?id=${encodeURIComponent(button.dataset.deleteTip)}`,{method:"DELETE"});notify("Aposta excluída","A lista foi atualizada.");await loadSuggestedBets();}catch(error){notify("Não foi possível excluir",error.message);}});}catch(error){grid.innerHTML=`<section class="panel premium-empty"><h2>Não foi possível carregar</h2><p>${escapeHtml(error.message)}</p></section>`;}}
  async function importFile(file,url,label){const box=byId("suggestedBetError");box.hidden=true;try{const payload=JSON.parse(await file.text()),result=await api(url,{method:"POST",body:JSON.stringify({payload,file_name:file.name})});notify(label,`${result.tips??result.results} registro(s) processado(s).`);await loadSuggestedBets();return true;}catch(error){box.textContent=error.message;box.hidden=false;return false;}}
  let selectedSuggestedFile=null;const publishSuggestedButton=byId("publishSuggestedBets");byId("selectSuggestedBetFile").onclick=()=>byId("suggestedBetFile").click();byId("suggestedBetFile").onchange=event=>{selectedSuggestedFile=event.target.files[0]||null;byId("suggestedBetFileName").textContent=selectedSuggestedFile?selectedSuggestedFile.name:"Nenhum arquivo selecionado";publishSuggestedButton.hidden=!selectedSuggestedFile;};publishSuggestedButton.onclick=async()=>{if(!selectedSuggestedFile)return;publishSuggestedButton.disabled=true;publishSuggestedButton.textContent="Publicando…";const published=await importFile(selectedSuggestedFile,"/api/admin-import-tips","Apostas publicadas");publishSuggestedButton.disabled=false;publishSuggestedButton.textContent="Publicar apostas sugeridas";if(published){selectedSuggestedFile=null;byId("suggestedBetFile").value="";byId("suggestedBetFileName").textContent="Nenhum arquivo selecionado";publishSuggestedButton.hidden=true;}};
  byId("selectSuggestedResultFile").onclick=()=>byId("suggestedResultFile").click();byId("suggestedResultFile").onchange=async event=>{const file=event.target.files[0];if(!file)return;byId("suggestedResultFileName").textContent=file.name;await importFile(file,"/api/admin-import-results","Resultados liquidados");event.target.value="";};
  document.querySelector('[data-page="suggested-bets"]').addEventListener("click",loadSuggestedBets);window.addEventListener("scannerday:authenticated",loadSuggestedBets);
})();
